# Generated by Django 5.1.5 on 2025-03-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_payment_options_rename_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
