# Generated by Django 5.1.5 on 2025-03-15 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_task_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='referred_by',
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
